### ISSUE TITLE
APS.DerivativesApi().getManifest always return 0% progress

### ISSUE THREAD

**Issue by lacmuch** [Autodesk-Forge/forge-api-nodejs-client#105]
If I call APS.DerivativesApi().translate and request the status of the translation on the uploaded .zip file, the progress in the object returned by APS.DerivativesApi().getManifest is always 0%, even after 5 minutes, even 1 second before the end of the translation. What can I do wrong?

**Comment by cyrillef** [comment]
Would you share the sample file for us to investigate? This isn't an issue with the SDK, so please report this to aps.help@autodesk.com
