### ISSUE TITLE
DerivativesApi.getDerivativeManifest() always returns a 400

### ISSUE THREAD

**Issue by instructaPhil** [Autodesk-Forge/forge-api-nodejs-client#11]
Looks like there's something wrong with the ```getDerivativeManifest()``` function. When I use it like this:

```
                DerivativesApi.getDerivativeManifest(designUrn, derivUrn, {}, oAuth2TwoLegged, credentials)
                .then(function(done){
                    console.log(done);
                })
                .catch(function(err){
                    console.log(err);
                })
```

I always get this:

```
{ statusCode: 400, statusMessage: 'Bad Request' }
```

But when I instead log out my access token and urn's into a formatted curl request, that curl request works just fine:

```
console.log("curl -X 'GET'  -H 'Authorization: Bearer "+credentials.access_token+"' -v 'https://developer.api.autodesk.com/modelderivative/v2/designdata/"+designUrn+"/manifest/"+derivUrn+"'");
```

That gives me a curl command that I can just run (**'d out some sensitive parts):
```
$ curl -X 'GET'  -H 'Authorization: Bearer v6MLmO8mIc8UPI*************' -v 'https://developer.api.autodesk.com/modelderivative/v2/designdata/dXJuOmFkc2sub2JqZWN0czpvcy5vYmplY3Q6aW5zdHJ1Y3RhYmxlcy1mb3JnZS1kZXYt*********/manifest/urn%3Aadsk.viewing%3Afs.file%3AdX**************JnZS1kZXYtYnVja2V0L3Rlc3Quc3Rs%2Foutput%2F1%2Ftest.svf.png01_thumb_100x100.png'
```

... and it spits out data:

```
?PNG

IHDRdp?Td??IDATx^?]il]?u??7?O\?MK?TY?#5??ڍ׵]'?? u??hS(? E?(Z???ڢ@k???hǱ?cɑ?X?eS?(??HJ?׷?g???3?Σ???A?{gΜ????v/C/??5??"????w?չ??Q????Z??ޫ?
                                                                                                                                        BGo?~J?????g"??Q?ՠ?&????R?}tJQS1???I[t???tKQ*8
```

Just FYI, there's a bug that deserves a failing unit test.

**Comment by gregra81** [comment]
@instructaPhil - Thanks for the heads up, I'll take a look at that

**Comment by gregra81** [comment]
@instructaPhil - Are you maybe encoding the derivUrn twice? This worked for me:

`
const designUrn = 'dXJuOmFkc2sub2JqZWN0czpvcy5vYmplY3Q6Z3JlZ19idWNrZXQvc3RsX3Rlc3Quc3Rs';
const derivUrn = 'urn:adsk.viewing:fs.file:dXJuOmFkc2sub2JqZWN0czpvcy5vYmplY3Q6Z3JlZ19idWNrZXQvc3RsX3Rlc3Quc3Rs/output/1/stl_test.svf';
DerivativesApi.getDerivativeManifest(designUrn, derivUrn, {}, oAuth2TwoLegged, credentials)
        .then(function(done){
            console.log(done);
        })
        .catch(function(err){
            console.log(err);
        })
`

But maybe you didn't notice and passed a urlencoded version of `derivUrn` into the function?

**Comment by instructaPhil** [comment]
Oh -- I definitely did. That's why the curl request works, definitely. Thanks for the heads-up!

FWIW, the [documentation in this repo](https://github.com/Autodesk-Forge/forge-api-nodejs-client/blob/master/docs/DerivativesApi.md#getDerivativeManifest) says to do that:

![image](https://cloud.githubusercontent.com/assets/4673350/22106802/625f1b12-ddff-11e6-9009-b5714dc90e5d.png)

So if the nodejs SDK does the url encoding for me, the docs should probably be changed.

Thanks!
