### ISSUE TITLE
autoRefresh example?

### ISSUE THREAD

**Issue by leefsmp** [Autodesk-Forge/forge-api-nodejs-client#14]
Can you show a concrete example using autoRefresh = true? Do my client code needs to pass a callback or can I assume calling `OAuth2TwoLegged.prototype.getCredentials` will always return a valid token? By looking at the implementation it seems to me autoRefresh is not doing anything ...

**Comment by cyrillef** [comment]
The autoRefresh code is [here](https://github.com/Autodesk-Forge/forge-api-nodejs-client/blob/master/src/ApiClient.js#L256). As you can see, the autoRefresh will run 300 seconds before the access_token expires and request a new token.

**Comment by leefsmp** [comment]
Can we change [this line](https://github.com/Autodesk-Forge/forge-api-nodejs-client/blob/master/src/ApiClient.js#L256) of code by the following, that would allow skipping the oauth2client and provide credentials refreshed by custom logic:

` 
if (**oauth2client &&** oauth2client.autoRefresh && new Date(credentials.expires_at - 300).getTime() <= Date.now()) {
`

Thanks

**Comment by gregra81** [comment]
@leefsmp, @cyrillef - fixed
