### ISSUE TITLE
DerivativesApi.getHierarchy(urn, guid, token, callback); (node:16284) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): [object Object]

### ISSUE THREAD

**Issue by kenken64** [Autodesk-Forge/forge-api-nodejs-client#18]
When calling this DerivativesApi.getHierarchy(urn, guid, token, callback);

it gives me the following error

(node:16284) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): [object Object]

**Comment by kenken64** [comment]
I kind of solve the promise rejection 

{"statusCode":400,"statusMessage":"Bad Request"}

now this really figure me ...

var jobPayload = new ForgeSDK.JobPayload();
jobPayload.input= "urn:" + new Buffer (urn).toString ('base64');

DerivativesApi.translate(jobPayload, opts, oAuth2TwoLegged, oAuth2TwoLegged.getCredentials())
    .then(function(response){
      console.log(response);
    }, function(err){
      console.log("<>>>>" + JSON.stringify(err));
    });

**Comment by gregra81** [comment]
@kenken64 - Thanks, we'll take a look at it

**Comment by gregra81** [comment]
@kenken64 - It looks like you're not building the `jobPayload` object correctly. Try doing:
```javascript
var jobPayload = new ForgeSDK.JobPayload();
jobPayload.input= {
  "urn": new Buffer(urn).toString('base64');
}
```
Also, the [documentation page](https://developer.autodesk.com/en/docs/model-derivative/v2/reference/http/job-POST/) says that the `output` attribute is mandatory, and you are not supplying it.
