### ISSUE TITLE
Allow for `state` in OAuth2ThreeLegged.generateAuthUrl

### ISSUE THREAD

**Issue by clowenhg** [Autodesk-Forge/forge-api-nodejs-client#19]
OAuth2ThreeLegged.generateAuthUrl does not allow a state to be added to the generated url.
Described here https://developer.autodesk.com/en/docs/oauth/v2/reference/http/authorize-GET/

**Comment by clowenhg** [comment]
#20

**Comment by akoskm** [comment]
Should be `state` optional?
