### ISSUE TITLE
getBuckets syntax

### ISSUE THREAD

**Issue by rodrigoprojetabim** [Autodesk-Forge/forge-api-nodejs-client#21]
1-) getBuckets doesn't work without a callback function(err). So, I suggest to add this callback to the sample.
2-) getBuckets need "buckets: read". The sample on this page suggest to use the "token that were obtained from the previous step". I suggest to add a comment "notice that you need do add a buckets: read permission"

**Comment by gregra81** [comment]
@rodrigoprojetabim - Thanks for the feedback!
