### ISSUE TITLE
Obtaining room/area information from forge api 

### ISSUE THREAD

**Issue by nasushkov** [Autodesk-Forge/forge-api-nodejs-client#25]
Hi
I need is to get room/area objects with the hierarchy of linked objects from the revit model. Right now I am using [this project](https://github.com/Autodesk-Forge/model.derivative-nodejs-sample) as a start point. Unfortunately, the room information in lost. As far as I understand, it is removed during the translation process. There are some workarounds like [this one](http://through-the-interface.typepad.com/through_the_interface/2016/06/getting-room-information-for-revit-models-in-the-forge-viewer.html), but it doesn't seem to work for our case. Is there any straightforward way to retrieve room information from rvt in Forge?

**Comment by gregra81** [comment]
@nasushkov - Since this question is not directly relates to the forge node client, I'm closing it. Please go to our support page here: https://developer.autodesk.com/en/support/get-help
