### ISSUE TITLE
`FoldersApi.postFolder` is missing pathParameter for `project_id`

### ISSUE THREAD

**Issue by alekperos** [Autodesk-Forge/forge-api-nodejs-client#28]
Hi dear team, 

The `postFolder` method of FoldersApi does not have a proper definition for `pathParams` which should include `project_id`.
https://github.com/Autodesk-Forge/forge-api-nodejs-client/blob/master/src/api/FoldersApi.js#L329 should be something like this:

`var pathParams = { project_id: body.projectID
      };` 

Also the documentation for:
https://github.com/Autodesk-Forge/forge-api-nodejs-client/blob/master/docs/CreateFolder.md
...is missing.

**Comment by gregra81** [comment]
@alekperos - Thanks for the input, we'll make sure to fix that

**Comment by gregra81** [comment]
@alekperos Fixed: `forge-apis@0.4.1`

Regarding documentation, please refer to this page:
https://developer.autodesk.com/en/docs/data/v2/reference/http/projects-project_id-folders-POST/
