### ISSUE TITLE
Header parameters are not appended to `ApiClient.callApi`

### ISSUE THREAD

**Issue by alekperos** [Autodesk-Forge/forge-api-nodejs-client#3]
Hi, 
I'm currently implementing the partial uploads of large files to the Forge platform, and encountered an issue which gives `{ statusCode: 400, statusMessage: 'Bad Request' }`. Digged the codebase and found that header parameters that are prepared in `ObjectsApi.uploadChunk`: 

``` 
 var headerParams = {
        'Content-Length': contentLength,
        'Content-Range': contentRange,
        'Content-Disposition': opts['contentDisposition'],
        'If-Match': opts['ifMatch'],
        'Session-Id': sessionId
      };
```

are sent to `ApiClient.callApi`, but those parameters are not actually added at all to the request, hence causing issues.

Can you please clarify this?

**Comment by gregra81** [comment]
@alekperos - Thanks for catching that bug. We're still in early beta with some of our SDKs and we missed that. Anyway, I issued a fix to this and it is now fixed on version 0.2.3.
