### ISSUE TITLE
[Feature Request] Add TypeScript definitions

### ISSUE THREAD

**Issue by Mika83AC** [Autodesk-Forge/forge-api-nodejs-client#34]
Hello Forge-Team,

I'd like to ask you to add TypeScript definitions for the NodeJS client. 

For us, TypeScript is crucial in our big projects, and as we want to make heavy use of Forge, we'd highly appreciate having TypeScript definitions for your API.

Regards,
Michael

**Comment by cyrillef** [comment]
We are working on something, but it is not ready yet
If you want I can send you what we got for now, just email me directly @ cyrille then autodesk.com

**Comment by CharlieBickerton** [comment]
Hi Forge-Team,

Is there any progress on this? I need type defs for a project.

Cheers guys.

**Comment by seabeams** [comment]
Hi Forge-Team,

Are there typescript definitions yet?

Thanks
