### ISSUE TITLE
Is this package still actively maintained?

### ISSUE THREAD

**Issue by nasushkov** [Autodesk-Forge/forge-api-nodejs-client#37]
I am little confused with the new [Autodesk Forge NextGen initiative.](https://forge.autodesk.com/blog/forge-nextgen-webinars-and-accelerator). Does it mean that Forge API will be significantly refactored in the near future and is this package still actively maintained? According to [this video](https://youtu.be/9IpE3JGgH7k?list=PL_6ApchKwjN9CZCqUl4RZrsyDvnTV1Jgb&t=1645) it looks like there will be a new SDK with several packages like @adsk/forge-appfw-core etc.

**Comment by cyrillef** [comment]
It is a different API, in addition to the current one - while the next one offer more capabilities

**Comment by nasushkov** [comment]
@cyrillef Thanks, looking forward to that
