### ISSUE TITLE
Missing definition of CreateFolder in FoldersApi.postFolder()

### ISSUE THREAD

**Issue by JohnOnSoftware** [Autodesk-Forge/forge-api-nodejs-client#45]
In the API [https://github.com/Autodesk-Forge/forge-api-nodejs-client/blob/master/docs/FoldersApi.md#postFolder](https://github.com/Autodesk-Forge/forge-api-nodejs-client/blob/master/docs/FoldersApi.md#postFolder), the definition of type CreateFolder is not actually defined, check [https://github.com/Autodesk-Forge/forge-api-nodejs-client/blob/master/docs/CreateFolder.md](https://github.com/Autodesk-Forge/forge-api-nodejs-client/blob/master/docs/CreateFolder.md)

**Comment by cyrillef** [comment]
fixed in version 0.5.0
