### ISSUE TITLE
Test are failing

### ISSUE THREAD

**Issue by jloracudris** [Autodesk-Forge/forge-api-nodejs-client#48]
Im trying to run the test, most of the are succesfull but theres 4 of them that are failing
![image](https://user-images.githubusercontent.com/17204647/52369442-b96fad00-2a1e-11e9-9917-447d0abfa163.png)

Can you guys help me fixing the test or point me in the right direction to run them succesfully

Thanks

@gregra81

**Comment by cyrillef** [comment]
Solved
