### ISSUE TITLE
npm contains version 0.4.5 while package.json lists 0.4.4

### ISSUE THREAD

**Issue by wwkeyboard** [Autodesk-Forge/forge-api-nodejs-client#57]
https://www.npmjs.com/package/forge-apis is different from https://github.com/Autodesk-Forge/forge-api-nodejs-client/blob/master/package.json#L3. I pulled the tarball from npm and it doesn't look like the code up there is different from what's in the repo.

This was a little confusing to me and I want to make sure there isn't anything missing from the repo.

**Comment by cyrillef** [comment]
Fixed - moved to version 0.5.2

**Comment by wwkeyboard** [comment]
Thank you!
