### ISSUE TITLE
Where to "run the following code"

### ISSUE THREAD

**Issue by SelaO-AL** [Autodesk-Forge/forge-api-nodejs-client#6]
It says in the readme to "run the following code" for the 2-legged and 3-legged tokens, but where this code is supposed to be placed?
I couldn't even find in any of the files 'CLIENT_ID'.

Edit:
So I placed the 2/3-legged code in a file and ran it with node, in the 3-legged `oAuth2ThreeLegged.generateAuthUrl();` doesn't return `authorizationCode` in the url, and if I try to navigate to that url, I get:

> {"developerMessage":"The required parameter(s) redirect_uri not present in the request","userMessage":"","errorCode":"AUTH-008","more info":"http://developer.api.autodesk.com/documentation/v1/errors/AUTH-008"}

**Comment by gregra81** [comment]
Hi,
Did you initialize the `oAuth2ThreeLegged` object like so:
`var oAuth2ThreeLegged = new ForgeSDK.AuthClientThreeLegged(CLIENT_ID, CLIENT_SECRET, REDIRECT_URL, [
    'data:read',
    'data:write'
]);`

Mind the `CLIENT_ID`, `CLIENT_SECRET`, `REDIRECT_URL` - you need to set them properly

**Comment by SelaO-AL** [comment]
I didn't set the `REDIRECT_URL`, now it worked.

**Comment by gregra81** [comment]
Great!
