### ISSUE TITLE
Is it possible to create project with this library

### ISSUE THREAD

**Issue by emptyHeap** [Autodesk-Forge/forge-api-nodejs-client#68]
I see no `AccountAdmin` class or `accounts` path in sources. Is there any plans to implement something like `AccountAdmin` class (create new project, create new company and activate service which are described in [this documentation](https://forge.autodesk.com/en/docs/bim360/v1/tutorials/account-admin/))

**Comment by cyrillef** [comment]
You are correct, we do not yet include BIM360 endpoints on that library
We are working on one, but no date as when it would be available
