### ISSUE TITLE
Type Definition

### ISSUE THREAD

**Issue by jjangga0214** [Autodesk-Forge/forge-api-nodejs-client#71]
I read #34.
It said it's working, but it's been a long time till now without any d.ts file or typescript rewrite. 
As there has been no reply to the last question about progess, hereby I open a new issue.

Is there any specific plan?

**Comment by cyrillef** [comment]
it has been published for quite a long time at https://www.npmjs.com/package/@types/forge-apis 

npm install --save-dev @types/forge-apis
