### ISSUE TITLE
ObjectsApi.uploadObject set x-ads-content-sha1 header

### ISSUE THREAD

**Issue by ilseva** [Autodesk-Forge/forge-api-nodejs-client#72]
Hi all,
I think that there is no way to set the x-ads-content-sha1 header using this wrapper.
You can pass the If-Match parameter, but according to API documentation they are different

**If-Match** | _When overwriting an object, use the latest SHA-1 hash to verify that you are overwriting the latest data.A SHA-1 hash is returned every time you upload or overwrite an object. If the SHA-1 hash in the header does not match the current SHA-1 hash stored for this object in OSS, the request fails (status code 412)._

**x-ads-content-sha1** | _A SHA-1 checksum of the object represented as a hexadecimal string.If the SHA-1 hash in the header does not match the SHA-1 hash computed by the server for the uploaded object, the request fails (status code 400)._

Thanks.

**Comment by cyrillef** [comment]
Hi, you are correct, I added this into the source code and will release a new version soon
