### ISSUE TITLE
Planning for Direct-to-S3 approach

### ISSUE THREAD

**Issue by amkoehler** [Autodesk-Forge/forge-api-nodejs-client#80]
Hello - recently it was [announced](https://forge.autodesk.com/blog/data-management-oss-object-storage-service-migrating-direct-s3-approach?mkt_tok=OTE4LUZPRC00MzMAAAGDf-cgFNUWM6UHCu-7e8lg4nYuby7Qx_SR89duHmebkGcvhvA76yFZPVFKPkhO4Nr3Nobk1d6ZByrgaYfvRNHL5bz7BD-d_JQctd1Zq22HbRbWi5mCAADN) that certain data management API calls would be deprecated in favor of direct uploads and downloads from the underlying AWS S3 bucket. We make use of a couple of methods in the `ObjectsApi` and I'm wondering if we'll need to plan for these changes or if this package will be handling that automatically. 

For example, we use `ObjectsApi.uploadChunk` for resumable uploads, which calls [this soon-to-be-deprecated method](https://forge.autodesk.com/en/docs/data/v2/reference/http/buckets-:bucketKey-objects-:objectKey-resumable-PUT/). Will `uploadChunk` be updated under the hood to call the new direct-to-s3 endpoint?

**Comment by sivanandh** [comment]
When we use this sample code to upload a file we are facing the issue that singedurl is not generating with the upload key.

when we try 3 or 4 times the same code is generating the correct upload key with singedurl however its failing for 8 out of 10 times
![upload_key_issue](https://user-images.githubusercontent.com/22432436/170424356-e66ee05b-f9cb-405f-bbb2-d495bc125b04.png)

**Comment by darkl1ght** [comment]
@augustogoncalves 

Hi, any updates on whether the ObjectsApi's methods getObjects() and uploadObject(), be internally updated and those using forge-apis npm package won't have to modify their code? This is with respect to the deprecation mail that was sent out in favor of a new set of Data Management API endpoints to allow direct upload and download from the underlying AWS S3 bucket.

> Hello - recently it was [announced](https://forge.autodesk.com/blog/data-management-oss-object-storage-service-migrating-direct-s3-approach?mkt_tok=OTE4LUZPRC00MzMAAAGDf-cgFNUWM6UHCu-7e8lg4nYuby7Qx_SR89duHmebkGcvhvA76yFZPVFKPkhO4Nr3Nobk1d6ZByrgaYfvRNHL5bz7BD-d_JQctd1Zq22HbRbWi5mCAADN) that certain data management API calls would be deprecated in favor of direct uploads and downloads from the underlying AWS S3 bucket. We make use of a couple of methods in the `ObjectsApi` and I'm wondering if we'll need to plan for these changes or if this package will be handling that automatically.
> 
> For example, we use `ObjectsApi.uploadChunk` for resumable uploads, which calls [this soon-to-be-deprecated method](https://forge.autodesk.com/en/docs/data/v2/reference/http/buckets-:bucketKey-objects-:objectKey-resumable-PUT/). Will `uploadChunk` be updated under the hood to call the new direct-to-s3 endpoint?

**Comment by cyrillef** [comment]
v0.9.1 implements the wrapper for directs3. it also introduces 2 generic methods to hide the complexity of using s3. They are called downloadResources() and uploadResources(), see samples/dmSample2.js and dmSample-complex.js for examples.

**Comment by cyrillef** [comment]
Hi, no reason to move to this function if you already using chunks.

**Comment by amkoehler** [comment]
Thanks @cyrillef. This has me a little confused on the deprecation. Under the hood, `uploadChunks` calls a [deprecated endpoint](https://aps.autodesk.com/en/docs/data/v2/reference/http/buckets-:bucketKey-objects-:objectKey-resumable-PUT/):

https://github.com/Autodesk-Forge/forge-api-nodejs-client/blob/48e79706b659552f75c8099c5e2131b68153df81/src/api/ObjectsApi.js#L184-L190

I opened #106 for a separate issue with `uploadResources`, so for now we're still on `uploadChunks`. Is there truly no reason to move if `uploadChunks` is calling a deprecated endpoint?
