### ISSUE TITLE
Expose ApiClient's callApi function (Feature Request)

### ISSUE THREAD

**Issue by ejisaac** [Autodesk-Forge/forge-api-nodejs-client#85]
While not strictly required, this would help developers with extending the API.

Some of the functionality in the HTTP Specification isn't implemented in the Node SDK, including the ability to search and filter users in BIM360 or ACC. https://forge.autodesk.com/en/docs/acc/v1/reference/http/users-search-GET/

As of now, this can be done through a direct HTTP request, but it seems like the ApiClient has some safeguards and quality of life checks already implemented. If possible, I'd prefer to reference this for writing extensions.

It would also be convenient with respect to authentication and general consistency with using the API. Extensions could be written to match the patterns that Autodesk has established within the API, allowing extensions to be easily replaced by official SDK functions as they are implemented.

**Comment by cyrillef** [comment]
You can already do this using:

```
const apiClient = new ForgeSDK.ApiClient();
apiClient.defaultHeaders = { 'x-ads-test': BUCKET_KEY };
...
apiClient.call (...);
```
see [sample](https://github.com/Autodesk-Forge/forge-api-nodejs-client/blob/master/samples/dmSample.js#L44)
