### ISSUE TITLE
ApiClient.convertToType is not a function

### ISSUE THREAD

**Issue by alekperos** [Autodesk-Forge/forge-api-nodejs-client#9]
Hi, 

Updated the SDK to the latest revision, now no longer able to submit a job for translation.
it gives an error when building a job object for translation function call:

```
    job = new ForgeAPI.JobPayload { 
        input: {
            urn: urn
       },
        output: {
            formats: [ {type: "svf", views: ["2d","3d"]} ]
        }
   }
```

`JobPayload` is using `JobPayloadInput` and `JobPayloadOutput` which use a method called `ApiClient.convertToType` that no longer exists. 

Can you please advice what to do?

**Comment by gregra81** [comment]
@alekperos - Sorry for the late response, I'll take a look at it and post a fix ASAP

**Comment by gregra81** [comment]
@alekperos - Check out version 0.2.7 where this is fixed. Thanks again for the heads up!

**Comment by alekperos** [comment]
Can you please update NPM accordingly? version is still 0.2.6 there.

**Comment by gregra81** [comment]
@alekperos - It's published now
