### ISSUE TITLE
Support for typescript as @types/forge-apis is outdated

### ISSUE THREAD

**Issue by Aarbel** [Autodesk-Forge/forge-api-nodejs-client#92]
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/forge-apis.

Hi Autodesk team, it would be really nice that you maintain the types repo in the same time you update the forge api packages.

Do you plan to provide it ? 

Thanks a lot

**Comment by cyrillef** [comment]
We will update it - but as we are moving to a TS-based implementation, I cannot guarantee we will prioritize this one. The new SDK should be available before AU (in a month time)

**Comment by Aarbel** [comment]
Thanks a lot @cyrillef
